# Syncs bitbucket repo to github

image: alpine/git

pipelines:
  branches:
    master:
      - step:
          script:
            - git remote add sync git@github.com:t-cc/pulseradeactividad.info.git
            - git checkout master
            - git pull
            - git push sync master
